### ISSUE TITLE
About  Intrinsic and Image Rectification

### ISSUE THREAD

**Issue by zzzh1y** [ShuweiShao/AF-SfMLearner#10]
作者你好~
我想问下关于内参和畸变矫正相关的问题。

1. 我注意到SCARED每个子数据集的内参并不完全一致，您是取了一个近似吗？
2. SCARED中endoscope_calibration.yaml中M1、D1与M2、D2是分别对应左右眼图像的内参吗？
3. 训练前需要对图像进行矫正吗？

感谢！

**Comment by ShuweiShao** [comment]
Hi,  
1. 我是多个子数据集的内参取得平均值；
2. 我的理解也是这样；
3. 我训练的时候没矫正，这个可以自己测试下；

**Comment by zzzh1y** [comment]
明白了，感谢回复！
