### ISSUE TITLE
test_sample

### ISSUE THREAD

**Issue by xwx0924** [ShuweiShao/AF-SfMLearner#11]
作者你好，请教您一个简单的问题，我从scared数据集提取了20张图片，下载了预训练的MIA模型对其预测（test_sample），得到了depth图和disp数组，但disp数组的大小是输入图像的1/4，请问代码里哪里可以控制这个输出的大小吗，我想获得和原图一样大小的数组。 还是只能像depth图一样在disp结果上进行插值。

**Comment by ShuweiShao** [comment]
您好，在options.py文件里可以控制，但模型是在1/4分辨率上训练的，所以最好是在1/4分辨率上训练，然后插值到最高分辨率

**Comment by xwx0924** [comment]
感谢您的回答！还有个问题请教您，我的输入是同一场景下的20张图片（scared数据集里一个视频里截取的），那预测出来的时候这20张图片之间的相对深度值会保持一致吗，还是每张图像的深度值是独立预测的~

**Comment by ShuweiShao** [comment]
不一定会保持一致，每张图像的深度值是独立预测的。

**Comment by xwx0924** [comment]
好的 谢谢解惑

**Comment by ShuweiShao** [comment]
或许我最近的一个工作[SMUDLP: Self-Teaching Multi-Frame Unsupervised Endoscopic Depth Estimation with Learnable Patchmatch](https://arxiv.org/abs/2205.15034)对你有帮助。

**Comment by xwx0924** [comment]
好的 谢谢~~
