### ISSUE TITLE
Why are the four corners of the predicted depth map black?

### ISSUE THREAD

**Issue by lby53** [ShuweiShao/AF-SfMLearner#12]
Why are the four corners of the predicted depth map black?

![image](https://user-images.githubusercontent.com/107620407/197162099-a07b5455-fffc-4a5f-a253-1f551762d5fc.png)

**Comment by ShuweiShao** [comment]
请问输入网络的时候有没有resize呢？网络训练的分辨率是256x320

**Comment by ShuweiShao** [comment]
您也可以自己训练一个网络，使用什么分辨率训练，最好使用什么分辨率测试，如果是加载给的模型，256x320的分辨率测试是最好的，代码里有resize函数，只需要将options里的参数改下就可以。

**Comment by lby53** [comment]
您好，我就是以320x320的图片作为输入自己训练的，训练加载了预训练模型，我是不是应该选择从头开始训练的方式。然后之前选择从头开始训练，不知道是数据量不够（12000张图片）或是epoch较少（30），预测出的深度图全是黄色。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShuweiShao/AF-SfMLearner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 上午9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShuweiShao/AF-SfMLearner] Why are the four corners of the predicted depth map black? (Issue #12)





 
您也可以自己训练一个网络，使用什么分辨率训练，最好使用什么分辨率测试，如果是加载给的模型，256x320的分辨率测试是最好的，代码里有resize函数，只需要将options里的参数改下就可以。

**Comment by ShuweiShao** [comment]
可以试试从头训，感觉12000张图片和30个epoch应该是够的，内参记得改一下。

**Comment by lby53** [comment]
好的，对于内窥镜鱼眼镜头拍摄的图片，是不是应该畸变校正后作为输入进行训练会更好。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShuweiShao/AF-SfMLearner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月27日(星期四) 上午9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShuweiShao/AF-SfMLearner] Why are the four corners of the predicted depth map black? (Issue #12)





 
可以试试从头训，感觉12000张图片和30个epoch应该是够的，内参记得改一下。

**Comment by ShuweiShao** [comment]
您好，鱼眼镜头我没有测试过，您可以自己测试下。

**Comment by wza527** [comment]
你好，我也是使用了Endoslam数据进行了训练，出现了预测出的深度图全是黄色的问题，请问你解决了吗？
![image](https://github.com/user-attachments/assets/e3de6b4a-bc1b-4f47-a8a7-748f2ba42c6d)
