### ISSUE TITLE
how to get poses_our.npz

### ISSUE THREAD

**Issue by sincerely1** [ShuweiShao/AF-SfMLearner#15]
您好，对于你们的研究工作表示感谢。在使用你们新添加的visualize_pose.py时，我不知道如何获取 pose_our.npz。npz这个内容是和evalute_pose.py一样直接通过网络输出test_file.txt的pose吗？我尝试了将evalute_pose.py输出的pred_poses保存，通过visualize_pose.py可视化后结果完全不同，可以介绍一下如何生成正确的pose_our.npz吗？

**Comment by sincerely1** [comment]
<a href="https://imgloc.com/i/ksk8q"><img src="https://i.328888.xyz/2023/01/08/ksk8q.md.png" alt="ksk8q.png" border="0" /></a>
这是我对论文中的trajectory-1 的结果，我不太清楚我哪里错了

**Comment by ShuweiShao** [comment]
看你描述的好像没问题，可以展示下你的代码不

**Comment by sincerely1** [comment]
预测部分代码：

    with torch.no_grad():
        for inputs in dataloader:
            for key, ipt in inputs.items():
                inputs[key] = ipt.cuda()

            all_color_aug = torch.cat([inputs[("color", 1, 0)], inputs[("color", 0, 0)]], 1)
            #print(inputs[("color", 1, 0)].shape)
            #print(all_color_aug.shape)
            features = [pose_encoder(all_color_aug)]
            axisangle, translation = pose_decoder(features)
            # print("旋转角度")
            # print(axisangle)
            # print("转换")
            # print(translation)

            pred_poses.append(
                transformation_from_parameters(axisangle[:, 0], translation[:, 0]).cpu().numpy())
            # print("pred_pose")
            # print(pred_poses)

    pred_poses = np.concatenate(pred_poses)
    output_path = os.path.join('./', "poses_our.npz")

    print("Saving to {}".format(opt.split))
    np.savez_compressed(output_path, data=np.array(pred_poses))`

**Comment by ShuweiShao** [comment]
你是用的我的预训练模型不

**Comment by sincerely1** [comment]
抱歉是我的问题，我使用的是我自己训练了20轮的模型，应该是训练时出了问题。使用你们提供的模型没有问题

**Comment by ShuweiShao** [comment]
Hi，请参考https://github.com/ShuweiShao/AF-SfMLearner/issues/8#issuecomment-1336339048， 好几个同学出现了你这个问题，目前已经解决。

**Comment by sincerely1** [comment]
感谢
&nbsp;


窗前明月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 上午9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ShuweiShao/AF-SfMLearner] how to get poses_our.npz (Issue #15)





 
Hi，请参考https://github.com/ShuweiShao/AF-SfMLearner/issues/8#issuecomment-1336339048， 好几个同学出现了你这个问题，目前已经解决。
