### ISSUE TITLE
非常感谢作者公开您的工作

### ISSUE THREAD

**Issue by 1158191255** [ShuweiShao/AF-SfMLearner#19]
顺便提一下，如果使用高版本torchvision，需要将mono_dataset.py中的`color_avg=transforms.ColorJitter.get_params(self.brightness,self.contrast,self.saturation,self.hue)`改成`color_avg=transforms.ColorJitter(self.brightness,self.contrast,self.saturation,self.hue)`
因为get_params这个函数在高版本里发生了修改。

**Comment by ShuweiShao** [comment]
谢谢您的提醒，我将会更新在Important Note中。
