### ISSUE TITLE
关于注意力模块

### ISSUE THREAD

**Issue by 1158191255** [ShuweiShao/AF-SfMLearner#21]
大佬您好，在前人的研究中，有人在位姿估计网络中加入了注意力机制。我在本项目中也进行了同样的尝试，但是加入了之后的深度、位姿评估指标均不及未加入之前，这个注意力模块似乎还起到了反作用。请问关于注意力机制模块在胸腔镜环境下的使用您有什么建议么。

**Comment by ShuweiShao** [comment]
您好，注意力模块并不一定有效，您可以多尝试不同的注意力机制，以及注意力机制的位置也会有影响。
