### ISSUE TITLE
训练集和验证集的划分，会不会导致数据泄露

### ISSUE THREAD

**Issue by Hellcat1005** [ShuweiShao/AF-SfMLearner#22]
您好，我看了splits/endovis下的数据划分，对于同一个dataset，有多个keyframe，这些keyframe有些分在训练集，有些分在验证集。但是这些都是属于同一个场景的，会不会导致数据泄露呢？我理解的划分应该是按照dataset去进行划分，比如说dataset 1 2 3 4 为训练，然后5为验证。不知道您当时是怎么考虑的？

**Comment by ShuweiShao** [comment]
您好，尽管是属于同一个场景，但是他们还是不同的视频，您的这种划分方式也是可以的。
