### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by han12580** [ShuweiShao/AF-SfMLearner#23]
您好！
请问论文中的scared测试结果是在endovis中test.txt文件中进行测试的吗？
![image](https://user-images.githubusercontent.com/94788634/230347917-0e189fee-a6f3-4a36-9ef6-a8855e5436f0.png)

**Comment by ShuweiShao** [comment]
是的

**Comment by han12580** [comment]
> 

好的，非常感谢
