### ISSUE TITLE
Inference in customer data

### ISSUE THREAD

**Issue by a227799770055** [ShuweiShao/AF-SfMLearner#24]
@ShuweiShao 感謝您的專案。目前我有自己的內視鏡影片，我如果想要透過您的模型與權重來去產生軌跡圖的話，我的影像資料需要做哪些前處理呢？此外我需要執行那一個檔案來進行推論呢？
謝謝

**Comment by ShuweiShao** [comment]
您好，预处理可以参考下代码的dataset部分，可视化摄像机轨迹可以参考https://github.com/ShuweiShao/AF-SfMLearner/issues/8

**Comment by a227799770055** [comment]
@ShuweiShao  Thanks!
