### ISSUE TITLE
EndoSLAM 數據集產出軌跡圖 ground true

### ISSUE THREAD

**Issue by a227799770055** [ShuweiShao/AF-SfMLearner#25]
@ShuweiShao 作者您好

想要請問在 [EndoSLAM](https://data.mendeley.com/datasets/cd2rtzm23r/1)數據集中如果要產生出如下圖的軌跡圖 ground true，該使用哪些數據呢？

![pose](https://user-images.githubusercontent.com/50135574/230834866-5c394fa9-d3a8-4ecc-801b-92774a000285.png)

**Comment by ShuweiShao** [comment]
您好，这两个轨迹是在scared数据集上的，数据请参考https://github.com/ShuweiShao/AF-SfMLearner/tree/main/splits/endovis
