### ISSUE TITLE
关于数据集的获取及其他问题

### ISSUE THREAD

**Issue by Danture** [ShuweiShao/AF-SfMLearner#27]
您好，因为我开始这方面的研究工作时间比较晚，我想在官网下载SCARED数据集但通道已关闭，不知道现在还有什么渠道可以获取该数据集吗？在没有SCARED数据集的情况下，我尝试在哈姆林数据集上复现您的工作，但测试结果和您论文中的相差较大。我发现结果和测试集的选取有关系，我将一个文件夹里的数据当作测试集，数据量达到3600多张图片，当我不断缩减时，结果表现也越来越好，我猜想数据量越大，相应均值的偏移就越大，会带来更大的偏差，不知道您在哈姆林数据集上测试时用了多少数据呢？
![捕获](https://user-images.githubusercontent.com/113769949/231111339-63e24551-3c34-4f5f-950b-a33708cd2d6d.PNG)
![捕获](https://user-images.githubusercontent.com/113769949/231111502-ba3514e3-7bb4-4a64-b43b-3053edc6606c.PNG)

**Comment by evanismli** [comment]
您好，请问您还有哈姆林的数据集吗？官方那里不能下载了..
