### ISSUE TITLE
Questions about the tiff files and the dataset structure

### ISSUE THREAD

**Issue by SeiyaIchijo** [ShuweiShao/AF-SfMLearner#29]
I really appreciate your contribution and I'm sorry to bother you with some problems I have encountered.

The first problem is about the tiff files. Are they supposed to be converted to png format? If so, how does it work?

Another question is about the dataset structure. I am quite confused, because after converting the mp4 file to png files I found the directory was like this: /endovis_or_scared/dataset_1/keyframe_1/data/image1.png("image1.png" was converted from the mp4 file). There is nothing corresponding to "image_02" mentioned in README. Could you please clarify this part in more details?

Thank you in advance for your kindness and help!

**Comment by ShuweiShao** [comment]
1. It can be converted into the png format, and the saving way can refer to the KITTI dataset.
2. image_02 is a folder and created by ourselves.

**Comment by SeiyaIchijo** [comment]
> 1. It can be converted into the png format, and the saving way can refer to the KITTI dataset.
> 2. image_02 is a folder and created by ourselves.

Thank you for your response! I would be grateful if you could answer the 2 further questions:

1. In Endovis or SCARED dataset there are some keyframe files without mp4 files. Should I just leave them there? Or there are some operations required?
2. Why is it necessary to create a folder like "image_02" when using Endovis or SCARED? What does this image_02 refer to? Can I simply use the data structure like this?
/path/to/endovis_data/
  dataset1/
    keyframe1/
        data/
          0000000001.png

Sorry for bothering you with these basic questions. Your time and effort are greatly appreciated!

**Comment by C-H-Chien** [comment]
您好，我也有相同的類似的問題：
1. 在原始的endovis_or_scared資料集下的data structure中，並沒有image_02這樣的folder，請問為何需要自行建立image_02呢？image_02代表的是left images嗎？如果不是，您將圖片分類在image_02 folder下的依據是什麼呢？
2. endovis_or_scared資料集中有些keyframe folder中沒有data這個folder，在此情況下我們直接不考慮該keyframe folder嗎？
非常謝謝您！

**Comment by ShuweiShao** [comment]
image_02文件夹用来存储left images； 对于没有data文件夹的keyframe，我们没有考虑。
