### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'endovis\\rectified11\\image_02\\-00001.png'

### ISSUE THREAD

**Issue by evanismli** [ShuweiShao/AF-SfMLearner#30]
![image](https://user-images.githubusercontent.com/56707899/232071859-ded9974a-bcb2-4374-86d9-1c3a697fe859.png)
![image](https://user-images.githubusercontent.com/56707899/232071914-0fb88bb3-11c8-479a-a776-98800ec7e528.png)
您好，我使用哈姆林数据集，但是将数据集中的image_02修改成了我自己的单目内镜照片，其余都是数据集本身的信息，使用python train_stage_one.py --data_path endovis --log_dir stage_one_result想训练深度估计网络，出现了以上错误，请问是否是由于本人数据集有问题导致的呢？谢谢，期待您的回复

**Comment by ShuweiShao** [comment]
It seems that the path to load image is wrong.

**Comment by evanismli** [comment]
> It seems that the path to load image is wrong.

您好，感谢您的回复，我检查了envodis文件夹下的图片以及两个txt文档，均不存在-0000.1.png存在。

**Comment by evanismli** [comment]
> It seems that the path to load image is wrong.

还有一个问题，就是我能否只用单目内镜图片利用您公布的网络进行深度估计训练呢？
谢谢

**Comment by ShuweiShao** [comment]
有连续帧或者视频是可以进行训练的，单张图片是不可以的

**Comment by ShuweiShao** [comment]
有连续帧或者视频是可以进行训练的，单张图片是不可以的

**Comment by yuyingliu-1** [comment]
> > It seems that the path to load image is wrong.
> 
> 您好，感谢您的回复，我检查了envodis文件夹下的图片以及两个txt文档，均不存在-0000.1.png存在。

这个原因是因为代码中用的frame_id - 1，如果测试集中有0000.png，导致成了-0001.png
