### ISSUE TITLE
预测结果

### ISSUE THREAD

**Issue by xwx0924** [ShuweiShao/AF-SfMLearner#31]
作者您好~~请问我用您的预训练模型运行test_simple.py得到的结果有对应图像的 image000_disp.npy，这个是视差图还是深度图呀~~

**Comment by ShuweiShao** [comment]
这个是视差图。

**Comment by xwx0924** [comment]
感谢您及时的回复，请问这种单目图像的视差图是取倒数就可以获得深度图么~~双目的是有个转换公式

**Comment by ShuweiShao** [comment]
不是，可以参考https://github.com/ShuweiShao/AF-SfMLearner/blob/main/layers.py中的disp_to_depth函数。
