### ISSUE TITLE
关于数据集预处理及测试精度的问题

### ISSUE THREAD

**Issue by Danture** [ShuweiShao/AF-SfMLearner#32]
您好，感谢公开您的结果，我想问一下拿到scared数据集后我应该做些什么预处理来得到可以用来训练的数据集结构呢？因为我对这个数据集的结构不理解，不清楚要用哪些文件来转换为另一些文件。我找到一个好像是其他工作者贡献的工具包，地址如下：https://github.com/dimitrisPs/scared_toolkit ，您当时是自己手动处理还是使用什么程序来处理的呢？

然后我之前下载了哈姆林数据集，我尝试取了6个内参相同的文件夹共两万多的图像构成数据集，划分为6：2：2，训练时使用了端到端的网络，测试结果出现了nan值，非常奇怪，当我以8：1：1划分再训练后，
测试结果大概为0.297  &  14.929  &  26.047  &   0.346  &   0.644  &   0.830  &   0.916 ，和您的结果仍有不小的差距，不知道您当时是怎么划分哈姆林数据集的，尤其是测试集的划分。

**Comment by ShuweiShao** [comment]
您好，关于scared数据的预处理，请参考readme中的Endovis data preprocessing部分。

我们当时并没有哈姆林数据集上训练，只是随机挑选了部分图片进行了泛化能力测试。
