### ISSUE TITLE
关于color_aug的报错：TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by bobcatcapoo** [ShuweiShao/AF-SfMLearner#33]
您好，非常感谢您的分享。我在进行stage0的时候遇到了标题中的报错，报错发生在mono_dataset.py的第104行：inputs[(n + "_aug", im, i)] = self.to_tensor(color_aug(f))。请问我需要在此处做出什么调整吗？

**Comment by ShuweiShao** [comment]
可能是由于安装的package的版本不同，产生的报错，是需要调整的。
