### ISSUE TITLE
关于测试集测试结果

### ISSUE THREAD

**Issue by Mar-lll** [ShuweiShao/AF-SfMLearner#34]
您好，感谢您公开您的工作。我们使用了endovis中的test_files_sequence1.txt序列进行测试，模型为Stage-wise (ID 5 in Table 8)。得到了如下的评价指标，可以看到指标和论文中的结果还存在着一定差距。想请教一下，这样的差距是合理的吗？
或者是不是出现了什么问题导致了这一结果。
![屏幕截图 2023-04-22 144907](https://user-images.githubusercontent.com/77665425/233770561-513636eb-5c89-40ee-a12a-27676dbfed37.png)

**Comment by ShuweiShao** [comment]
test_files_sequence1.txt不是深度估计的测试集，[test_files.txt](https://github.com/ShuweiShao/AF-SfMLearner/blob/main/splits/endovis/test_files.txt)这个是深度估计的测试集，有没有在这个txt文件上测试过呢？

**Comment by Mar-lll** [comment]
感谢您的回答，我们目前只在test_files_sequence1.txt上进行了测试。之后我们会尝试用test_files.txt进行测试
