### ISSUE TITLE
关于scene_points000389.tiff': can't open/read file: check file path/integrity

### ISSUE THREAD

**Issue by bobcatcapoo** [ShuweiShao/AF-SfMLearner#37]
作者您好，我正在使用Endovis or SCARED数据集进行Endovis Evaluation。我将scene_points.tar.gz解压得到一系列.tiff文件，然而在dataset3/keyframe4中遇到如下报错：
/endovis_or_scared/dataset3/keyframe4/image_02/data/scene_points000389.tiff'): can't open/read file: check file path/integrity
但我的dataset3/keyframe4中.tiff文件编号最大只有000115。请问我需要修改文件编号或者代码吗？感谢您的耐心，希望能得到解答。

**Comment by ShuweiShao** [comment]
您好，文件编号和代码是不需要修改的，会不会是您下载的数据集和我当时使用的数据集有轻微的不一样呢？还有一个可能会不会是keyframe的序号不太对，我的id是从1开始的，不是从0。
