### ISSUE TITLE
在evaluation后显示Killed

### ISSUE THREAD

**Issue by bobcatcapoo** [ShuweiShao/AF-SfMLearner#38]
您好，抱歉再次打扰。在用Endovis or SCARED进行evaluation的过程中，执行到export_gt_depth.py中的np.savez_compressed(output_path, data=np.array(gt_depths))指令时，程序显示了Killed。请问这是出于什么原因呢？会与内存有关吗？

**Comment by ShuweiShao** [comment]
您好，有没有再次尝试呢，我没有遇到过这种情况。

**Comment by bobcatcapoo** [comment]
> 您好，有没有再次尝试呢，我没有遇到过这种情况。

是memory的问题，现已解决。谢谢您
