### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system.

### ISSUE THREAD

**Issue by bobcatcapoo** [ShuweiShao/AF-SfMLearner#39]
您好，我正在使用Endovis or SCARED进行evaluation，在evaluate_depth.py的evaluate(options.parse())和encoder.cuda()出现了报错信息：RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
运行这一步时我使用的是cpu，请问有办法规避这个报错吗？感谢您的解答

**Comment by ShuweiShao** [comment]
您好，您把.cuda()去掉就可以了。
