### ISSUE TITLE
Multiple questions about errors, 'weights' and visualization

### ISSUE THREAD

**Issue by bobcatcapoo** [ShuweiShao/AF-SfMLearner#40]
作者您好，我在用Endovis or SCARED完成training和evaluation后遇到一些问题，希望能得到您的解答

1. 我的evaluation结果如下
   abs_rel |       sq_rel |     rmse |       rmse_log |       a1 |        a2 |          a3 | 
&   0.066  &   0.605  &   5.895  &   0.094  &   0.962  &   0.995  &   0.998  \\
请问这个结果是否偏大呢？

2. 在进行evaluation和prediction时，我遇到如下warining message
/anaconda3/lib/python3.10/site-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  warnings.warn(
/anaconda3/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
请问这些warining message会影响我的结果吗？

3. 进行prediction后我得到了depth map，但您的代码似乎没有直接将诸如optical flow, appearance flow以及3d reconstruction可视化。请问如果我想可视化这些内容的话需要进行什么额外的操作吗？

抱歉我的问题可能比较复杂，非常感谢您的时间与精力！

**Comment by ShuweiShao** [comment]
1. 您好，您是采用的给的权重进行评估还是自己训练的权重？
2. 这个warning之前我没有遇到过，不确定会不会影响精度。
3. 光流的可视化可以参考下光流估计的文章，appearance flow的可视化可以参考https://github.com/ShuweiShao/AF-SfMLearner/issues/7， 3D重建的可视化可以参考论文中的github链接。

**Comment by bobcatcapoo** [comment]
> 

谢谢您的回复！我使用的是自己训练的权重

**Comment by ShuweiShao** [comment]
您用给定的权重测试的结果是多少，先排除下是否是数据集划分的原因？

**Comment by cccrystalyang** [comment]
Hi, I also encountered the same problem. I have preprocessed the dataset using the author's update method, and the code 'align_corner' are also set to True. The same results as mentioned in the paper can be obtained using the weights provided by the author, but the results of retraining DepthNet with the given OFNet weights also remain around 0.061. May I ask what optimizations and adjustments have you made? @adam99goat @ShuweiShao

**Comment by bobcatcapoo** [comment]
> 

您好，请问您的意思是我需要用Endovis or SCARED本身给定的test_dataset_8和test_dataset_9进行evaluation和test嘛？

**Comment by bobcatcapoo** [comment]
> 您用给定的权重测试的结果是多少，先排除下是否是数据集划分的原因？

您好，请问您的意思是我需要用Endovis or SCARED本身给定的test_dataset_8和test_dataset_9进行evaluation和test嘛？

**Comment by ShuweiShao** [comment]
不是的，指的是AF-SfMLearner中的test set
