### ISSUE TITLE
Endovis 551 frames in test dataset 

### ISSUE THREAD

**Issue by ItsShi** [ShuweiShao/AF-SfMLearner#41]
您好，非常感谢您公开您的工作！
我在运行export_gt_depth.py和evaluate_depth.py时遇到了些问题：可以请问Endovis(SCARED)测试集中的551帧对应的ground truth是怎么得到的吗？我在数据集中只能找个几十张关键帧的tiff深度图。

**Comment by ShuweiShao** [comment]
您好，在scene_points中。

**Comment by ItsShi** [comment]
请问可以提供一下论文中做定性分析的图5中所选择的4帧SCARED图像是具体哪一个数据集中的第几帧吗？非常感谢！

**Comment by ShuweiShao** [comment]
您好，最近有点忙，所以回复的有点晚。

第一行来自dataset1/keyframe3的394帧，第二行来自dataset2/keyframe4的1319帧，第四行来自dataset4/keyframe4的132帧，第三行来自dataset5/keyframe4的101帧。

由于时间过去了很久，上述的细节可能会有错误，还请验证下。
