### ISSUE TITLE
ResNet endcoder

### ISSUE THREAD

**Issue by Huster-Hq** [ShuweiShao/AF-SfMLearner#42]
Hi, thanks for your fantastic work. I find the **_resnet_encoder.py_** is different from Monodepth2. Specially, the difference occurs below. 

![image](https://github.com/ShuweiShao/AF-SfMLearner/assets/100923014/db837b9f-5892-49bd-a6e2-d5e2ec039f64)
I am curious about that. 

Look forward to your reply~

**Comment by ShuweiShao** [comment]
Hi, thanks for your attention. Since 0.45 and 0.25 are derived from natural images and may not be suitable for endoscopic images, we removed them. But from our experiments, there is little effect on the accuracy.
