### ISSUE TITLE
How did you obtain endovis/train_files.txt? Did you randomly shuffle it?

### ISSUE THREAD

**Issue by Weijun-Lin** [ShuweiShao/AF-SfMLearner#43]
Hello, thanks for your work!

How did you obtain "endovis/train_files.txt"? Did you randomly shuffle it?
Why not directly input the ordered video sequence?

**Comment by ShuweiShao** [comment]
Hi, sorry for the late reply. 
I established the split by referring to the split on the KITTI dataset, and  have randomly shuffled it following previous work , such as sfmlearner.

**Comment by Weijun-Lin** [comment]
Thank you for your reply. May I ask why shuffle operation is needed? Will training on shuffled sequences be better than training on the original ordered sequences?

**Comment by ShuweiShao** [comment]
The shuffle operation can improve the robustness of the network. I guess training on shuffled sequences may work better, but haven't tested it.

**Comment by Weijun-Lin** [comment]
I see. Thanks a lot!
