### ISSUE TITLE
3d reconstructions

### ISSUE THREAD

**Issue by evanismli** [ShuweiShao/AF-SfMLearner#44]
您好，我尝试对您的工作进行了复现，但有一个问题想请教您，就是关于重建部分，请问您在进行重建操作时是直接参考了Endo-Depth-and-Motion 中的Volumetric fusion部分么？期待您的回复。谢谢

**Comment by ShuweiShao** [comment]
是这样的

**Comment by evanismli** [comment]
感谢您的回复，在Volumetric fusion时需要用到一个.pkl文件，请问这个文件您是如何生成的呢？
