### ISSUE TITLE
SCARED point cloud acc and EndoSLAM

### ISSUE THREAD

**Issue by shanwq** [ShuweiShao/AF-SfMLearner#45]
作者您好！
我想问一下，scared数据集的点云精度是如何得到的呀？将depth转为点云之后如何计算accuracy呢？
还有就是EndoSLAM的五折交叉验证，是用上了LowCam所有的帧吗？因为我看您似乎没有用scared所有的帧。
以上两部分的结果，不知道您方不方便提供一下代码。如果可以的话，真是非常感谢了。如有打扰，还望海涵！

**Comment by ShuweiShao** [comment]
您好，不好意思，刚注意到这个问题。Accuracy这儿指的是RMSE，与深度误差的计算类似。EndoSLAM的五折交叉验证用了所有的帧。代码我找找看，时间有点长了。
