### ISSUE TITLE
Do you disable SSIM loss in training?

### ISSUE THREAD

**Issue by Weijun-Lin** [ShuweiShao/AF-SfMLearner#48]
I found that the ssim loss is disabled in MonodepthOptions by default, and I don't see ssim setting in readme.

**Comment by ShuweiShao** [comment]
We used the SSIM loss during training. For details, please refer to the options.py.

**Comment by Weijun-Lin** [comment]
> We used the SSIM loss during training. For details, please refer to the options.py.

The option.py is https://github.com/ShuweiShao/AF-SfMLearner/blob/main/options.py.

Lines 135-137 of code:
```python
  self.parser.add_argument("--no_ssim",
                           help="if set, disables ssim in the loss",
                           action="store_true")
```
I think it is true by default.

**Comment by ShuweiShao** [comment]
Sorry, this is False by default since we do not add --no_ssim in the training command

**Comment by Weijun-Lin** [comment]
> Sorry, this is False by default since we do not add --no_ssim in the training command

I got it! Thanks~
