### ISSUE TITLE
关于数据结构

### ISSUE THREAD

**Issue by DavidLuBit** [ShuweiShao/AF-SfMLearner#50]
您好~我想问一下关于数据结构的问题，就是在您定义的dataset1/keyframe1/image_02/data/路径中，image_02是如何定义的呢？从endovis网站下载的数据路径为dataset1/keyframe1/data/，谢谢！

**Comment by ShuweiShao** [comment]
Hi， image_02是自己创建的文件夹，用于放左目的图像。
