### ISSUE TITLE
How many epochs should be set for end-to-end fashion?

### ISSUE THREAD

**Issue by Edwinzero-Miracle** [ShuweiShao/AF-SfMLearner#52]
Hi Shuwei,

I tried to reproduce the results by following the readme, everything works fine but it seems that there is a performance drop when I use the default parameters in train_end_to_end.py.

Could you specify the most reasonable training setting for this end-to-end configuration? Many thx!

**Comment by ShuweiShao** [comment]
Hi, what performance have you achieved?  The results of training in the end-to-end fasion are slightly worse than those of training in the stage-wise fasion.

**Comment by Edwinzero-Miracle** [comment]
Here are the results that I got.
-> Evaluating
EP20 

   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.065  &   0.563  &   5.712  &   0.092  &   0.961  &   0.996  &   0.999  \\

EP20 + 20 
-> Evaluating

   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.064  &   0.552  &   5.623  &   0.090  &   0.964  &   0.996  &   0.999  \\

**Comment by ShuweiShao** [comment]
Have you evaluated other epoches? such as 15, 16, 17, 18, 19.

**Comment by Edwinzero-Miracle** [comment]
The training configuration is :
epoch 20, not use --use_stereo, other args are using default parameters

Here are the results of weights 14 - 19 (EP15-20)

weights_14:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.064  &   0.548  &   5.631  &   0.091  &   0.961  &   0.996  &   0.999  \\

weights_15:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.064  &   0.543  &   5.607  &   0.090  &   0.963  &   0.996  &   0.999  \\

weights_16:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.063  &   0.543  &   5.620  &   0.090  &   0.963  &   0.996  &   0.999  \\

weights_17:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.064  &   0.548  &   5.645  &   0.090  &   0.962  &   0.996  &   0.999  \\

weights_18:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.064  &   0.549  &   5.662  &   0.091  &   0.963  &   0.996  &   0.999  \\

weights_19:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.065  &   0.563  &   5.712  &   0.092  &   0.961  &   0.996  &   0.999  \\

**Comment by ShuweiShao** [comment]
It seems very unreasonable. Which version of pytorch have you tried?

**Comment by Edwinzero-Miracle** [comment]
My env version python 3.9.7 and pytorch 2.0.1+cu118

**Comment by Edwinzero-Miracle** [comment]
Thanks for your timely help. I just sent a description of the problem to your institution's e-mail, perhaps we can discuss it more.
