### ISSUE TITLE
预测结果误差

### ISSUE THREAD

**Issue by yangkunyi** [ShuweiShao/AF-SfMLearner#54]
您好，非常感谢您公开您的工作。

我尝试按照readme中给的方式进行复现，我选择了end to end fashion的模型，使用了endovis的splits和默认的parameters，并且按照important note进行了修改。我的环境是py3.12_cuda12.1_cudnn8.9.2_0。 以下是我得到的结果。

weights_14:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.066  &   0.543  &   5.451  &   0.090  &   0.957  &   0.997  &   1.000  \\

weights_15:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.066  &   0.530  &   5.353  &   0.089  &   0.958  &   0.998  &   1.000  \\

weights_16:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.063  &   0.508  &   5.281  &   0.087  &   0.963  &   0.997  &   1.000  \\

weights_17:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.064  &   0.518  &   5.346  &   0.088  &   0.961  &   0.997  &   1.000  \\

weights_18:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.065  &   0.533  &   5.409  &   0.089  &   0.959  &   0.997  &   1.000  \\

weights_19:
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.066  &   0.543  &   5.451  &   0.090  &   0.958  &   0.997  &   1.000  \\

我认为我的结果与 issue #52  中的结果较为相似。
请问您认为可能的原因是什么呢？

**Comment by ShuweiShao** [comment]
您好，可能是环境不同导致的，我当时跑的环境是 PyTorch 1.2.0, torchvision 0.4.0, CUDA 10.2, Python 3.7.3 and Ubuntu 18.04

**Comment by yangkunyi** [comment]
> 您好，可能是环境不同导致的，我当时跑的环境是 PyTorch 1.2.0, torchvision 0.4.0, CUDA 10.2, Python 3.7.3 and Ubuntu 18.04

谢谢，我会尝试使用您提供的环境进行训练。
