### ISSUE TITLE
How to visualize the appear flow results

### ISSUE THREAD

**Issue by cccrystalyang** [ShuweiShao/AF-SfMLearner#7]
Dear Shuwei,
  Thanks for sharing the great work. I am a student and I have a problem when visualizing the appearance flow images. I would really appreciate it if you could provide some advice.
  I noticed that you showed the visualization of the appearance flows in Fig.5 of your published paper. But after I load the model and weights, the visualization of the appearance flow is far from your paper, as shown in the figure below. How did you visualize the appearance flow? The key code I use is as follows: trans_viz = transforms.ToPILImage()(output[('transform',0)].squeeze(dim=0).cpu()). 
  Looking forward to your reply.
![appear_flow](https://user-images.githubusercontent.com/114375208/192224242-44b0bb3f-5e4e-4199-a1d3-70df8fa8e0e7.png)

**Comment by ShuweiShao** [comment]
Hi, please refer to the following code:
import matplotlib as mpl
import matplotlib.cm as cm
transform_outputs = transform_decoder(transform_features)[("transform", 0)]
transform = torch.abs(transform_outputs.permute(0, 2, 3, 1))
transform_np = transform.squeeze().cpu().numpy().mean(2)
vmax = np.percentile(transform_np, 95)
normalizer = mpl.colors.Normalize(vmin=transform_np.min(), vmax=vmax)  # 归一化到0-1
mapper = cm.ScalarMappable(norm=normalizer, cmap='viridis')  # colormap
colormapped_im = (mapper.to_rgba(transform_np)[:, :, :3] * 255).astype(np.uint8)
Then, you could use the matplotlib.pyplot to visusalize colormapped_im.

**Comment by cccrystalyang** [comment]
Thanks for your quick reply.
I understand that your method is to visualize the three channels of appearance flow after averaging them.  After fine tuning, I obtain the visualization of the appearance flow in your paper. 

Further, how to apply the appearance flow to the source image?The results in your paper are satisfactory. I use the following code to obtain the recovery map directly, but the recovery map is noisy, as shown in the following figure. 
`transform_outputs = transform_decoder(transform_features)[("transform", 0)]
output = transform_outputs + image1`

Thank you very much for your help.
![refinedImag](https://user-images.githubusercontent.com/114375208/192286357-8a2fb8c2-830f-4922-992d-dcb30075f847.png)

**Comment by cccrystalyang** [comment]
Thank you for your prompt reply and the patient answer. I'm rechecking the code.

**Comment by cccrystalyang** [comment]
Thank you for your reply and help. 
My problem has been solved. 
Look forward to your next work.
Best wishes.

**Comment by ShuweiShao** [comment]
Thank you!

**Comment by bobcatcapoo** [comment]
> Hi, please refer to the following code: import matplotlib as mpl import matplotlib.cm as cm transform_outputs = transform_decoder(transform_features)[("transform", 0)] transform = torch.abs(transform_outputs.permute(0, 2, 3, 1)) transform_np = transform.squeeze().cpu().numpy().mean(2) vmax = np.percentile(transform_np, 95) normalizer = mpl.colors.Normalize(vmin=transform_np.min(), vmax=vmax) mapper = cm.ScalarMappable(norm=normalizer, cmap='viridis') # colormap colormapped_im = (mapper.to_rgba(transform_np)[:, :, :3] * 255).astype(np.uint8) Then, you could use the matplotlib.pyplot to visusalize colormapped_im.

您好，请问此处的“transform_features”指的是什么呢？
